env:
    # es6: true
    es2023: true
    node: true
    # commonjs: false
extends:
    - airbnb-base
    # - eslint:recommended
    - prettier
parserOptions:
    ecmaVersion: 2023
    sourceType: module
    requireConfigFile: false
    babelOptions:
        plugins:
            - '@babel/plugin-syntax-import-assertions'
parser: '@babel/eslint-parser'    
rules:
    prettier/prettier: error
    import/no-unresolved: 2
    import/no-commonjs: 2
    import/extensions: [2, "ignorePackages"]
plugins:
    - prettier
    - import
globals:
    beforeAll: readonly
    afterAll: readonly
    describe: readonly
    expect: readonly
    test: readonly
    it: readonly
