name: released

on:
  release:
    types: [published]

permissions: {}

jobs:
  virustotal:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'pull_request' &&
      github.repository_owner == 'ptarmiganlabs'

    steps:
      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@936d8c5c00afe97d3d9a1af26d017cfdf26800a2 # v5.0.0
        with:
          vt_api_key: ${{ secrets.VIRUSTOTAL_API_KEY }}
          request_rate: 4
          update_release_body: true
          files: |
            .zip$
